---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - "**.rb"
  - "bin/*"
  - "exe/*"
exclude_paths:
- carat.gemspec
- "*.md"
- lib/carat/ssl_certs/*.pem
- lib/carat/vendor/**/*
- lib/carat/templates/**/*.tt
- man/*
- spec/**/*
- Rakefile
