language: ruby
script: rake spec:travis
before_script:
 - gem uninstall bundler
 - travis_retry rake spec:travis:deps
sudo: required

rvm:
  - 2.2

# Rubygems versions MUST be available as rake tasks
# see Rakefile:66 for the list of possible RGV values
env:
  # We need to know if changes to rubygems will break bundler on release
  - RGV=master
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v2.7.2

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      env: RGV=master
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
