#!/usr/bin/env ruby
# frozen_string_literal: true

# Exit cleanly from an early interrupt
Signal.trap("INT") do
  Carat.ui.debug("\n#{caller.join("\n")}") if defined?(Carat)
  exit 1
end

require "carat"
# Check if an older version of carat is installed
$LOAD_PATH.each do |path|
  next unless path =~ %r{/carat-0\.(\d+)} && $1.to_i < 9
  err = String.new
  err << "Looks like you have a version of carat that's older than 0.9.\n"
  err << "Please remove your old versions.\n"
  err << "An easy way to do this is by running `gem cleanup carat`."
  abort(err)
end

require "carat/friendly_errors"
Carat.with_friendly_errors do
  require "carat/cli"

  # Allow any command to use --help flag to show help for that command
  help_flags = %w[--help -h]
  help_flag_used = ARGV.any? {|a| help_flags.include? a }
  args = help_flag_used ? Carat::CLI.reformatted_help_args(ARGV) : ARGV

  Carat::CLI.start(args, :debug => true)
end
